-- Air Ocean Line HR v1 migration
-- Run after the current v0.9 schema. Safe to rerun.

create extension if not exists pgcrypto;

-- ---------------------------------------------------------------------
-- Account mapping: every employee logs in with Supabase Auth.
-- Owner/HR remain in app_admins; employees are mapped here.
-- ---------------------------------------------------------------------
create table if not exists employee_accounts (
  user_id uuid primary key references auth.users(id) on delete cascade,
  employee_id bigint unique references employees(id) on delete cascade,
  role text not null default 'employee' check (role in ('employee','hr','owner')),
  active boolean not null default true,
  created_at timestamptz default now()
);

alter table employee_accounts enable row level security;

drop policy if exists employee_accounts_self_select on employee_accounts;
create policy employee_accounts_self_select
on employee_accounts for select to authenticated
using (user_id = auth.uid() or is_hr());

drop policy if exists employee_accounts_owner_all on employee_accounts;
create policy employee_accounts_owner_all
on employee_accounts for all to authenticated
using (is_owner()) with check (is_owner());

-- ---------------------------------------------------------------------
-- Company location / holidays / QR / notifications.
-- ---------------------------------------------------------------------
create table if not exists company_locations (
  id bigint generated by default as identity primary key,
  label text not null,
  lat numeric(12,8) not null,
  lng numeric(12,8) not null,
  radius_m int not null default 50,
  active boolean not null default true,
  created_at timestamptz default now()
);

insert into company_locations(label, lat, lng, radius_m, active)
select 'Air Ocean Line - Alexandria', 31.19845420, 29.90387470, 50, true
where not exists (select 1 from company_locations where active);

create table if not exists official_holidays (
  holiday_date date primary key,
  label text not null,
  created_by uuid references auth.users(id),
  created_at timestamptz default now()
);

create table if not exists daily_qr_codes (
  work_date date primary key,
  code text not null,
  created_by uuid references auth.users(id),
  created_at timestamptz default now()
);

create table if not exists notifications (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  target_role text check (target_role in ('employee','hr','owner','admin')),
  title text not null,
  body text not null,
  read_at timestamptz,
  created_at timestamptz default now()
);

alter table company_locations enable row level security;
alter table official_holidays enable row level security;
alter table daily_qr_codes enable row level security;
alter table notifications enable row level security;

drop policy if exists company_locations_read on company_locations;
create policy company_locations_read on company_locations for select to authenticated using (true);

drop policy if exists company_locations_owner_write on company_locations;
create policy company_locations_owner_write on company_locations for all to authenticated
using (is_owner()) with check (is_owner());

drop policy if exists official_holidays_read on official_holidays;
create policy official_holidays_read on official_holidays for select to authenticated using (true);

drop policy if exists official_holidays_hr_write on official_holidays;
create policy official_holidays_hr_write on official_holidays for all to authenticated
using (is_hr()) with check (is_hr());

drop policy if exists daily_qr_hr_read on daily_qr_codes;
create policy daily_qr_hr_read on daily_qr_codes for select to authenticated using (is_hr());

drop policy if exists notifications_read on notifications;
create policy notifications_read on notifications for select to authenticated
using (
  user_id = auth.uid()
  or (target_role = 'admin' and is_hr())
  or (target_role = 'hr' and is_hr())
  or (target_role = 'owner' and is_owner())
);

drop policy if exists notifications_update_read on notifications;
create policy notifications_update_read on notifications for update to authenticated
using (user_id = auth.uid()) with check (user_id = auth.uid());

-- ---------------------------------------------------------------------
-- Existing table extensions.
-- ---------------------------------------------------------------------
alter table attendance add column if not exists device_id text;
alter table attendance add column if not exists latitude numeric(12,8);
alter table attendance add column if not exists longitude numeric(12,8);
alter table attendance add column if not exists gps_accuracy int;
alter table attendance add column if not exists location_distance_m int;
alter table attendance add column if not exists qr_code text;
alter table attendance add column if not exists corrected_by uuid references auth.users(id);
alter table attendance add column if not exists corrected_at timestamptz;
alter table attendance add column if not exists correction_reason text;

alter table attendance drop constraint if exists attendance_status_check;
alter table attendance add constraint attendance_status_check
  check (status in ('present','late','absent','leave','mission','sick','pending'));

alter table permissions add column if not exists hours_requested numeric(3,1);
alter table permissions add column if not exists hours_approved numeric(3,1);
alter table permissions add column if not exists requested_by uuid references auth.users(id);
alter table permissions add column if not exists decision_note text;

update permissions set hours_requested = coalesce(hours_requested, hours)
where hours_requested is null;

alter table leave_requests add column if not exists requested_by uuid references auth.users(id);
alter table leave_requests add column if not exists decision_note text;

-- Employee read policies for their own records.
drop policy if exists att_employee_read on attendance;
create policy att_employee_read on attendance for select to authenticated
using (
  exists (
    select 1 from employee_accounts ea
    where ea.user_id = auth.uid()
      and ea.employee_id = attendance.employee_id
      and ea.active
  )
);

drop policy if exists permissions_employee_read on permissions;
create policy permissions_employee_read on permissions for select to authenticated
using (
  exists (
    select 1 from employee_accounts ea
    where ea.user_id = auth.uid()
      and ea.employee_id = permissions.employee_id
      and ea.active
  )
);

drop policy if exists leave_employee_read on leave_requests;
create policy leave_employee_read on leave_requests for select to authenticated
using (
  exists (
    select 1 from employee_accounts ea
    where ea.user_id = auth.uid()
      and ea.employee_id = leave_requests.employee_id
      and ea.active
  )
);

-- ---------------------------------------------------------------------
-- Helpers.
-- ---------------------------------------------------------------------
create or replace function geo_distance_meters(lat1 numeric, lng1 numeric, lat2 numeric, lng2 numeric)
returns numeric language sql immutable as $$
  select 6371000 * 2 * asin(sqrt(
    power(sin(radians(($3 - $1)::double precision) / 2), 2) +
    cos(radians($1::double precision)) * cos(radians($3::double precision)) *
    power(sin(radians(($4 - $2)::double precision) / 2), 2)
  ))::numeric;
$$;

create or replace function current_employee_id()
returns bigint language sql stable security definer set search_path=public as $$
  select employee_id from employee_accounts where user_id = auth.uid() and active limit 1;
$$;

create or replace function notify_user(p_user uuid, p_title text, p_body text)
returns void language sql security definer set search_path=public as $$
  insert into notifications(user_id,title,body) values (p_user,p_title,p_body);
$$;

create or replace function notify_admins(p_title text, p_body text)
returns void language sql security definer set search_path=public as $$
  insert into notifications(user_id,target_role,title,body)
  select user_id, 'admin', p_title, p_body from app_admins;
$$;

create or replace function ensure_daily_qr(p_date date)
returns text language plpgsql security definer set search_path=public as $$
declare
  v_code text;
begin
  select code into v_code from daily_qr_codes where work_date = p_date;
  if v_code is null then
    v_code := upper(substr(md5(p_date::text || ':' || gen_random_uuid()::text), 1, 6));
    insert into daily_qr_codes(work_date, code, created_by)
    values (p_date, v_code, auth.uid())
    on conflict (work_date) do nothing;
    select code into v_code from daily_qr_codes where work_date = p_date;
  end if;
  return v_code;
end $$;

-- ---------------------------------------------------------------------
-- Context and QR.
-- ---------------------------------------------------------------------
create or replace function get_my_context_v1()
returns jsonb language plpgsql security definer set search_path=public as $$
declare
  v_admin app_admins%rowtype;
  v_account employee_accounts%rowtype;
  v_employee jsonb;
  v_location jsonb;
  v_role text := 'employee';
  v_email text;
begin
  select email into v_email from auth.users where id = auth.uid();
  select * into v_admin from app_admins where user_id = auth.uid();
  select * into v_account from employee_accounts where user_id = auth.uid() and active;

  if v_admin.user_id is not null then
    v_role := v_admin.role;
  elsif v_account.user_id is not null then
    v_role := v_account.role;
  end if;

  if v_account.employee_id is not null then
    select to_jsonb(e.*) into v_employee from employees e where e.id = v_account.employee_id;
  end if;

  select to_jsonb(cl.*) into v_location
  from company_locations cl
  where cl.active
  order by cl.id
  limit 1;

  return jsonb_build_object(
    'role', v_role,
    'admin_name', coalesce(v_admin.name, v_email),
    'employee', v_employee,
    'location', v_location,
    'today', (now() at time zone 'Africa/Cairo')::date
  );
end $$;

create or replace function get_daily_qr_v1()
returns jsonb language plpgsql security definer set search_path=public as $$
declare
  v_date date := (now() at time zone 'Africa/Cairo')::date;
  v_code text;
begin
  if not is_hr() then
    return jsonb_build_object('error','hr_only','message','للإدارة فقط.');
  end if;
  v_code := ensure_daily_qr(v_date);
  return jsonb_build_object('date', v_date, 'code', v_code);
end $$;

-- ---------------------------------------------------------------------
-- Employee GPS/QR attendance.
-- ---------------------------------------------------------------------
create or replace function employee_attendance_action_v1(
  p_kind text,
  p_lat numeric,
  p_lng numeric,
  p_accuracy int,
  p_qr_code text,
  p_device_id text
)
returns jsonb language plpgsql security definer set search_path=public as $$
declare
  v_emp bigint;
  v_name text;
  v_now timestamp := now() at time zone 'Africa/Cairo';
  v_date date;
  v_time time;
  v_location company_locations%rowtype;
  v_distance numeric;
  v_qr text;
  s_start time;
  s_absent time;
  v_min int;
  v_late int;
  v_tier jsonb;
  v_tiers jsonb;
  v_status text := 'pending';
  v_label text := '';
  v_cut numeric := 0;
  v_att attendance%rowtype;
begin
  v_date := v_now::date;
  v_time := v_now::time;

  select employee_id into v_emp from employee_accounts where user_id = auth.uid() and active;
  if v_emp is null then
    return jsonb_build_object('error','no_employee','message','الحساب غير مربوط بموظف.');
  end if;

  select name into v_name from employees where id = v_emp;

  if extract(dow from v_date)::int = 5 or exists(select 1 from official_holidays where holiday_date = v_date) then
    return jsonb_build_object('error','holiday','message','اليوم أجازة رسمية أو راحة أسبوعية.');
  end if;

  select * into v_location from company_locations where active order by id limit 1;
  if not found then
    return jsonb_build_object('error','no_location','message','موقع الشركة غير مضبوط.');
  end if;

  v_distance := geo_distance_meters(p_lat,p_lng,v_location.lat,v_location.lng);
  if v_distance > v_location.radius_m then
    return jsonb_build_object('error','outside','message','أنت خارج نطاق الشركة. المسافة: ' || round(v_distance)::text || ' متر.');
  end if;

  v_qr := ensure_daily_qr(v_date);
  if upper(trim(coalesce(p_qr_code,''))) <> upper(v_qr) then
    return jsonb_build_object('error','bad_qr','message','كود QR غير صحيح.');
  end if;

  select * into v_att from attendance where employee_id = v_emp and work_date = v_date;

  if p_kind = 'in' then
    if found and v_att.check_in is not null then
      return jsonb_build_object('error','already','message','سجلت حضورك بالفعل.');
    end if;

    select (value#>>'{}')::time into s_start from settings where key='work_start';
    select (value#>>'{}')::time into s_absent from settings where key='absent_after';
    select value into v_tiers from settings where key='late_tiers';

    v_min := extract(hour from v_now)::int*60 + extract(minute from v_now)::int;
    v_late := greatest(0, v_min - (extract(hour from s_start)::int*60 + extract(minute from s_start)::int));

    if v_time >= s_absent then
      v_status := 'pending'; v_label := 'بعد 10:00 · موافقة المدير'; v_cut := 0;
    else
      for v_tier in select * from jsonb_array_elements(v_tiers) loop
        if v_late <= (v_tier->>'upto')::int then
          v_status := v_tier->>'status';
          v_label := v_tier->>'label';
          v_cut := (v_tier->>'cut')::numeric;
          exit;
        end if;
      end loop;
    end if;

    insert into attendance(employee_id,work_date,check_in,status,late_minutes,deduction_days,source,approved,recorded_by,device_id,latitude,longitude,gps_accuracy,location_distance_m,qr_code)
    values (v_emp,v_date,v_time,v_status,v_late,v_cut,'employee_app',false,auth.uid(),p_device_id,p_lat,p_lng,p_accuracy,round(v_distance),v_qr)
    on conflict (employee_id,work_date) do update
      set check_in = excluded.check_in,
          status = excluded.status,
          late_minutes = excluded.late_minutes,
          deduction_days = excluded.deduction_days,
          source = 'employee_app',
          recorded_by = auth.uid(),
          device_id = excluded.device_id,
          latitude = excluded.latitude,
          longitude = excluded.longitude,
          gps_accuracy = excluded.gps_accuracy,
          location_distance_m = excluded.location_distance_m,
          qr_code = excluded.qr_code;

    insert into audit_log(actor,action,entity,entity_id,details)
    values (auth.uid(),'employee_checkin','attendance',v_emp::text,jsonb_build_object('date',v_date,'time',v_time,'distance',round(v_distance)));

    perform notify_user(auth.uid(),'تم تسجيل الحضور','الوقت ' || to_char(v_time,'HH24:MI') || ' · ' || v_label);
    return jsonb_build_object('ok',true,'status',v_status,'time',to_char(v_time,'HH24:MI'),'label',v_label,'lateMin',v_late,'deductionDays',v_cut);
  elsif p_kind = 'out' then
    if not found or v_att.check_in is null then
      return jsonb_build_object('error','no_checkin','message','لازم تسجل حضور الأول.');
    end if;
    if v_att.check_out is not null then
      return jsonb_build_object('error','already','message','سجلت انصرافك بالفعل.');
    end if;

    update attendance
    set check_out = v_time,
        device_id = coalesce(device_id,p_device_id),
        latitude = coalesce(latitude,p_lat),
        longitude = coalesce(longitude,p_lng),
        gps_accuracy = coalesce(gps_accuracy,p_accuracy),
        location_distance_m = coalesce(location_distance_m,round(v_distance))
    where employee_id = v_emp and work_date = v_date;

    insert into audit_log(actor,action,entity,entity_id,details)
    values (auth.uid(),'employee_checkout','attendance',v_emp::text,jsonb_build_object('date',v_date,'time',v_time,'distance',round(v_distance)));

    perform notify_user(auth.uid(),'تم تسجيل الانصراف','الوقت ' || to_char(v_time,'HH24:MI'));
    return jsonb_build_object('ok',true,'time',to_char(v_time,'HH24:MI'));
  end if;

  return jsonb_build_object('error','bad_kind','message','نوع العملية غير صحيح.');
end $$;

-- ---------------------------------------------------------------------
-- Employee requests without PIN.
-- ---------------------------------------------------------------------
create or replace function request_permission_v1(p_date date, p_hours_requested numeric, p_reason text)
returns jsonb language plpgsql security definer set search_path=public as $$
declare
  v_emp bigint := current_employee_id();
  v_limit int;
  v_count int;
  v_today date := (now() at time zone 'Africa/Cairo')::date;
begin
  if v_emp is null then return jsonb_build_object('error','no_employee','message','الحساب غير مربوط بموظف.'); end if;
  if p_hours_requested not in (1,2) then return jsonb_build_object('error','bad_hours','message','مدة الإذن ساعة أو ساعتين.'); end if;
  if p_date < v_today then return jsonb_build_object('error','past_date','message','لا يمكن طلب إذن لتاريخ سابق.'); end if;
  if coalesce(trim(p_reason),'') = '' then return jsonb_build_object('error','reason_required','message','لازم تكتب سبب الإذن.'); end if;

  select coalesce((select (value#>>'{}')::int from settings where key='monthly_permission_max'),3) into v_limit;
  select count(*) into v_count from permissions
  where employee_id=v_emp and status in ('pending','approved')
    and date_trunc('month',perm_date)=date_trunc('month',p_date);
  if v_count >= v_limit then return jsonb_build_object('error','limit','message','وصلت الحد الأقصى للأذونات الشهرية.'); end if;

  if exists (
    select 1 from permissions
    where employee_id=v_emp and status in ('pending','approved')
      and perm_date in (p_date - interval '1 day', p_date + interval '1 day')
  ) then
    return jsonb_build_object('error','consecutive','message','غير مسموح بإذنين في يومين متتاليين.');
  end if;

  insert into permissions(employee_id,perm_date,hours,hours_requested,reason,status,requested_by)
  values (v_emp,p_date,p_hours_requested,p_hours_requested,p_reason,'pending',auth.uid());

  perform notify_admins('طلب إذن جديد','يوجد طلب إذن جديد يحتاج موافقة.');
  return jsonb_build_object('ok',true,'message','تم إرسال طلب الإذن.');
end $$;

create or replace function decide_permission_v1(p_id bigint, p_approve boolean, p_hours_approved numeric, p_note text default null)
returns jsonb language plpgsql security definer set search_path=public as $$
declare
  v permissions%rowtype;
  v_user uuid;
begin
  if not is_hr() then return jsonb_build_object('error','hr_only','message','للإدارة فقط.'); end if;
  select * into v from permissions where id=p_id;
  if not found then return jsonb_build_object('error','not_found','message','الطلب غير موجود.'); end if;
  if p_approve and p_hours_approved not in (1,2) then return jsonb_build_object('error','bad_hours','message','مدة الموافقة ساعة أو ساعتين.'); end if;

  update permissions
  set status = case when p_approve then 'approved' else 'rejected' end,
      hours_approved = case when p_approve then p_hours_approved else null end,
      decision_note = p_note,
      decided_at = now(),
      decided_by = auth.uid()
  where id=p_id;

  select user_id into v_user from employee_accounts where employee_id = v.employee_id;
  perform notify_user(v_user, case when p_approve then 'تمت الموافقة على الإذن' else 'تم رفض الإذن' end,
    case when p_approve then 'المدة المعتمدة: ' || p_hours_approved::text || ' ساعة.' else coalesce(p_note,'تم رفض الطلب.') end);

  return jsonb_build_object('ok',true);
end $$;

create or replace function leave_work_days_v1(p_from date, p_to date)
returns int language sql stable as $$
  select count(*)::int from generate_series(p_from,p_to,interval '1 day') d
  where extract(dow from d)::int <> 5
    and not exists (
      select 1 from official_holidays h
      where h.holiday_date = d::date
    );
$$;

create or replace function request_leave_v1(p_from date, p_to date, p_cover bigint, p_reason text)
returns jsonb language plpgsql security definer set search_path=public as $$
declare
  v_emp bigint := current_employee_id();
  v_days int;
  v_used numeric;
  v_today date := (now() at time zone 'Africa/Cairo')::date;
  v_balance numeric;
begin
  if v_emp is null then return jsonb_build_object('error','no_employee','message','الحساب غير مربوط بموظف.'); end if;
  if p_from <= v_today then return jsonb_build_object('error','too_late','message','الأجازة لازم قبلها بيوم على الأقل.'); end if;
  if p_to < p_from then return jsonb_build_object('error','bad_dates','message','تاريخ النهاية غير صحيح.'); end if;
  if p_cover is null or p_cover = v_emp then return jsonb_build_object('error','cover','message','لازم تختار Cover مختلف.'); end if;
  if coalesce(trim(p_reason),'') = '' then return jsonb_build_object('error','reason_required','message','لازم تكتب سبب الأجازة.'); end if;

  v_days := leave_work_days_v1(p_from,p_to);
  if v_days <= 0 then return jsonb_build_object('error','bad_days','message','الفترة لا تحتوي أيام عمل.'); end if;
  if v_days > 2 then return jsonb_build_object('error','max_days','message','الحد الأقصى يومين شهريًا.'); end if;

  if exists (
    select 1 from leave_requests
    where employee_id=v_emp and status in ('pending','approved')
      and (from_date in (p_from - interval '1 day', p_to + interval '1 day')
        or to_date in (p_from - interval '1 day', p_to + interval '1 day'))
  ) then
    return jsonb_build_object('error','consecutive','message','غير مسموح بأجازات متتالية.');
  end if;

  select coalesce(sum(days),0) into v_used from leave_requests
  where employee_id=v_emp and status in ('pending','approved')
    and date_trunc('month',from_date)=date_trunc('month',p_from);
  if v_used + v_days > 2 then return jsonb_build_object('error','monthly_limit','message','تجاوزت حد الأجازات الشهري.'); end if;

  select leave_balance into v_balance from employees where id=v_emp;
  if coalesce(v_balance,0) < v_days then return jsonb_build_object('error','balance','message','رصيد الأجازات غير كافي.'); end if;

  insert into leave_requests(employee_id,from_date,to_date,days,cover_employee_id,reason,status,requested_by)
  values (v_emp,p_from,p_to,v_days,p_cover,p_reason,'pending',auth.uid());

  perform notify_admins('طلب أجازة جديد','يوجد طلب أجازة جديد يحتاج موافقة.');
  return jsonb_build_object('ok',true,'message','تم إرسال طلب الأجازة.');
end $$;

create or replace function decide_leave_v1(p_id bigint, p_approve boolean, p_note text default null)
returns jsonb language plpgsql security definer set search_path=public as $$
declare
  v leave_requests%rowtype;
  v_user uuid;
  d date;
begin
  if not is_hr() then return jsonb_build_object('error','hr_only','message','للإدارة فقط.'); end if;
  select * into v from leave_requests where id=p_id;
  if not found then return jsonb_build_object('error','not_found','message','الطلب غير موجود.'); end if;

  update leave_requests
  set status = case when p_approve then 'approved' else 'rejected' end,
      decision_note = p_note,
      decided_at = now(),
      decided_by = auth.uid()
  where id=p_id;

  select user_id into v_user from employee_accounts where employee_id = v.employee_id;

  if p_approve then
    update employees set leave_balance = greatest(0,coalesce(leave_balance,0)-v.days) where id=v.employee_id;
    for d in select generate_series(v.from_date,v.to_date,interval '1 day')::date loop
      if extract(dow from d)::int <> 5 then
        insert into attendance(employee_id,work_date,status,late_minutes,deduction_days,note,source,approved,recorded_by)
        values (v.employee_id,d,'leave',0,0,'أجازة معتمدة · Cover: ' || v.cover_employee_id,'hr',true,auth.uid())
        on conflict (employee_id,work_date) do update
          set status='leave', check_in=null, check_out=null, late_minutes=0, deduction_days=0,
              note=excluded.note, source='hr', approved=true, recorded_by=auth.uid();
      end if;
    end loop;
  end if;

  perform notify_user(v_user, case when p_approve then 'تمت الموافقة على الأجازة' else 'تم رفض الأجازة' end,
    coalesce(p_note, case when p_approve then 'تم اعتماد طلب الأجازة.' else 'تم رفض طلب الأجازة.' end));

  return jsonb_build_object('ok',true);
end $$;

-- ---------------------------------------------------------------------
-- Admin operations.
-- ---------------------------------------------------------------------
create or replace function reset_attendance_day_v1(p_employee_id bigint, p_date date, p_reason text)
returns jsonb language plpgsql security definer set search_path=public as $$
declare
  v_old jsonb;
begin
  if not is_owner() then return jsonb_build_object('error','owner_only','message','Owner فقط يقدر يمسح سجل اليوم.'); end if;
  select to_jsonb(a.*) into v_old from attendance a where employee_id=p_employee_id and work_date=p_date;
  delete from attendance where employee_id=p_employee_id and work_date=p_date;
  insert into audit_log(actor,action,entity,entity_id,details)
  values (auth.uid(),'reset_attendance','attendance',p_employee_id::text,jsonb_build_object('date',p_date,'reason',p_reason,'old',v_old));
  return jsonb_build_object('ok',true);
end $$;

create or replace function set_official_holiday_v1(p_date date, p_label text)
returns jsonb language plpgsql security definer set search_path=public as $$
begin
  if not is_hr() then return jsonb_build_object('error','hr_only','message','للإدارة فقط.'); end if;
  insert into official_holidays(holiday_date,label,created_by)
  values (p_date,coalesce(nullif(trim(p_label),''),'أجازة رسمية'),auth.uid())
  on conflict (holiday_date) do update set label=excluded.label, created_by=auth.uid();
  insert into audit_log(actor,action,entity,entity_id,details)
  values (auth.uid(),'set_holiday','official_holidays',p_date::text,jsonb_build_object('label',p_label));
  return jsonb_build_object('ok',true);
end $$;

create table if not exists missing_checkout_counters (
  employee_id bigint not null references employees(id) on delete cascade,
  work_month text not null,
  warning_count int not null default 0,
  deduction_count int not null default 0,
  primary key(employee_id, work_month)
);

create or replace function mark_missing_checkouts_v1(p_date date)
returns jsonb language plpgsql security definer set search_path=public as $$
declare
  r record;
  v_month text := to_char(p_date,'YYYY-MM');
  v_count int;
  v_user uuid;
begin
  if not is_hr() then return jsonb_build_object('error','hr_only','message','للإدارة فقط.'); end if;
  for r in
    select * from attendance
    where work_date=p_date and check_in is not null and check_out is null and status in ('present','late')
  loop
    insert into missing_checkout_counters(employee_id,work_month,warning_count)
    values (r.employee_id,v_month,1)
    on conflict (employee_id,work_month)
    do update set warning_count = missing_checkout_counters.warning_count + 1
    returning warning_count into v_count;

    select user_id into v_user from employee_accounts where employee_id = r.employee_id;

    if v_count <= 2 then
      perform notify_user(v_user,'تنبيه عدم تسجيل انصراف','دي المرة رقم ' || v_count::text || ' في الشهر.');
    else
      update attendance
      set deduction_days = coalesce(deduction_days,0) + 0.25,
          note = coalesce(note || ' · ','') || 'خصم ربع يوم لعدم تسجيل الانصراف'
      where id = r.id;
      update missing_checkout_counters
      set deduction_count = deduction_count + 1
      where employee_id = r.employee_id and work_month = v_month;
      perform notify_user(v_user,'خصم عدم تسجيل انصراف','تم تطبيق خصم ربع يوم بعد تكرار عدم تسجيل الانصراف.');
    end if;
  end loop;
  return jsonb_build_object('ok',true);
end $$;

create or replace function owner_list_employee_accounts_v1()
returns table(
  employee_id bigint,
  employee_name text,
  user_id uuid,
  email text,
  role text,
  active boolean
)
language sql security definer set search_path=public as $$
  select
    e.id as employee_id,
    e.name as employee_name,
    ea.user_id,
    u.email,
    ea.role,
    coalesce(ea.active,false) as active
  from employees e
  left join employee_accounts ea on ea.employee_id = e.id
  left join auth.users u on u.id = ea.user_id
  where e.active
  order by e.id;
$$;

create or replace function owner_link_employee_account_v1(
  p_employee_id bigint,
  p_email text,
  p_role text default 'employee'
)
returns jsonb language plpgsql security definer set search_path=public as $$
declare
  v_user uuid;
begin
  if not is_owner() then
    return jsonb_build_object('error','owner_only','message','Owner فقط يقدر يربط حسابات الموظفين.');
  end if;

  if p_role not in ('employee','hr','owner') then
    return jsonb_build_object('error','bad_role','message','الدور غير صحيح.');
  end if;

  if not exists (select 1 from employees where id=p_employee_id and active) then
    return jsonb_build_object('error','employee_not_found','message','الموظف غير موجود أو غير نشط.');
  end if;

  select id into v_user
  from auth.users
  where lower(email) = lower(trim(p_email))
  limit 1;

  if v_user is null then
    return jsonb_build_object('error','auth_user_missing','message','اعمل حساب Auth بالإيميل ده الأول من Supabase Authentication.');
  end if;

  delete from employee_accounts
  where employee_id = p_employee_id and user_id <> v_user;

  insert into employee_accounts(user_id,employee_id,role,active)
  values (v_user,p_employee_id,p_role,true)
  on conflict (user_id) do update
    set employee_id=excluded.employee_id,
        role=excluded.role,
        active=true;

  insert into audit_log(actor,action,entity,entity_id,details)
  values (auth.uid(),'link_employee_account','employee_accounts',p_employee_id::text,jsonb_build_object('email',p_email,'role',p_role));

  return jsonb_build_object('ok',true);
end $$;

-- Grants
grant select on kiosk_employees to authenticated;
grant select on company_locations, official_holidays to authenticated;
grant select on daily_qr_codes to authenticated;
grant select, update on notifications to authenticated;
grant select on employee_accounts to authenticated;
grant execute on function get_my_context_v1() to authenticated;
grant execute on function get_daily_qr_v1() to authenticated;
grant execute on function employee_attendance_action_v1(text,numeric,numeric,int,text,text) to authenticated;
grant execute on function request_permission_v1(date,numeric,text) to authenticated;
grant execute on function decide_permission_v1(bigint,boolean,numeric,text) to authenticated;
grant execute on function request_leave_v1(date,date,bigint,text) to authenticated;
grant execute on function decide_leave_v1(bigint,boolean,text) to authenticated;
grant execute on function reset_attendance_day_v1(bigint,date,text) to authenticated;
grant execute on function set_official_holiday_v1(date,text) to authenticated;
grant execute on function mark_missing_checkouts_v1(date) to authenticated;
grant execute on function owner_list_employee_accounts_v1() to authenticated;
grant execute on function owner_link_employee_account_v1(bigint,text,text) to authenticated;
