-- #####################################################################
--  Air Ocean Line — Attendance System · SQL الكامل (النسخة النهائية)
--  يجمع كل الموديولات بالترتيب الصح. شغّله مرة واحدة:
--  Supabase → SQL Editor → الصق الكل → Run   (آمن تعيد تشغيله)
--  بعد التشغيل: اعمل حسابين Owner + HR (التعليمات في الآخر).
-- #####################################################################

-- ========== الجزء 1/4 — الأساس + الأدوار + إخفاء المرتبات ==========
-- =====================================================================
--  Air Ocean Line — Attendance · Schema v3
--  (Module 1: الأدوار HR/Owner + إخفاء المرتبات + الخصم ككسر يوم)
--  شغّله مرة واحدة بدل أي ملف قبله.  SQL Editor → الصق الكل → Run
--  آمن تعيد تشغيله.
-- =====================================================================

create extension if not exists pgcrypto;

-- ---- 1) Admins + Roles (hr / owner) ----
create table if not exists app_admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  name text, role text not null default 'hr' check (role in ('hr','owner')),
  created_at timestamptz default now()
);
alter table app_admins add column if not exists role text not null default 'hr';

create or replace function is_hr() returns boolean
language sql stable security definer set search_path=public as $$
  select exists (select 1 from app_admins where user_id=auth.uid());
$$;
create or replace function is_owner() returns boolean
language sql stable security definer set search_path=public as $$
  select exists (select 1 from app_admins where user_id=auth.uid() and role='owner');
$$;

-- ---- 2) Settings ----
create table if not exists settings (
  key text primary key, value jsonb not null, note text, updated_at timestamptz default now()
);
insert into settings(key,value,note) values
  ('work_start','"09:00"','بداية الدوام'),
  ('grace_mins','15','فترة السماح'),
  ('absent_after','"10:00"','بعدها = معلّق'),
  ('checkin_from','"08:30"','بداية نافذة الحضور'),
  ('checkin_to','"10:00"','نهاية نافذة الحضور'),
  ('checkout_from','"16:30"','بداية نافذة الانصراف'),
  ('checkout_to','"20:00"','نهاية نافذة الانصراف'),
  ('checkout_grace_to','"17:00"','انصراف لحد الساعة دي بدون خصم'),
  ('daily_wage_divisor','30','الأجر اليومي = المرتب ÷ 30'),
  ('annual_leave_days','21','الرصيد السنوي'),
  ('monthly_leave_max','2','حد أقصى أجازة شهريًا'),
  ('monthly_permission_max','3','حد أقصى إذن شهريًا'),
  ('late_tiers','[
     {"upto":15,"status":"present","label":"في الميعاد","cut":0},
     {"upto":30,"status":"late","label":"تأخير · تنبيه","cut":0},
     {"upto":45,"status":"late","label":"تأخير · إنذار شفهي","cut":0},
     {"upto":60,"status":"late","label":"تأخير · خصم ربع يوم","cut":0.25}
   ]','شرائح التأخير'),
  ('points','{"onTime":2,"lateMinor":0,"lateMajor":-1,"absent":-3}','النقاط')
on conflict (key) do nothing;
update settings set value='"08:30"' where key='checkin_from';
update settings set value='"10:00"' where key='checkin_to';

-- ---- 3) Employees (بدون مرتب) ----
create table if not exists employees (
  id bigint generated by default as identity primary key,
  name text not null, pin_hash text,
  leave_balance numeric(5,1) default 10, annual_entitlement int default 21,
  active boolean default true, created_at timestamptz default now()
);
alter table employees drop column if exists salary;   -- المرتب اتنقل لجدول منفصل

create or replace function set_employee_pin(p_emp bigint, p_pin text)
returns void language sql security definer set search_path=public, extensions as $$
  update employees set pin_hash=crypt(p_pin, gen_salt('bf')) where id=p_emp;
$$;
create or replace view kiosk_employees with (security_invoker=off) as
  select id, name, active from employees where active;

insert into employees(name,leave_balance)
select v.name,10 from (values('أبرار'),('ندى'),('إسراء'),('ياسمين'),('آلاء'),
  ('رودينا'),('ميروان'),('روان'),('حبيبة'),('عبدالرحمن'),('سهيلة'),('عمر')) as v(name)
where not exists (select 1 from employees);
select set_employee_pin(e.id, v.p) from (values
  ('أبرار','4023'),('ندى','1190'),('إسراء','7754'),('ياسمين','3318'),
  ('آلاء','8602'),('رودينا','5247'),('ميروان','9061'),('روان','2835'),
  ('حبيبة','6479'),('عبدالرحمن','1503'),('سهيلة','7128'),('عمر','3994')
) as v(nm,p) join employees e on e.name=v.nm;

-- ---- 4) Salaries (OWNER فقط — مخفي تمامًا عن HR) ----
create table if not exists salaries (
  employee_id bigint primary key references employees(id) on delete cascade,
  monthly_salary numeric(12,2) not null check (monthly_salary>=0),
  updated_at timestamptz default now()
);
insert into salaries(employee_id, monthly_salary)
select e.id, v.s from (values
  ('أبرار',10000),('ندى',7000),('إسراء',5000),('ياسمين',4500),('آلاء',5000),
  ('رودينا',4000),('ميروان',6000),('روان',3400),('حبيبة',3750),
  ('عبدالرحمن',2300),('سهيلة',1700),('عمر',5000)
) as v(nm,s) join employees e on e.name=v.nm
where not exists (select 1 from salaries);

-- ---- 5) Attendance (الخصم ككسر يوم، مش جنيه) ----
create table if not exists attendance (
  id bigint generated by default as identity primary key,
  employee_id bigint not null references employees(id) on delete cascade,
  work_date date not null, check_in time, check_out time,
  status text not null check (status in ('present','late','absent','leave','pending')),
  late_minutes int default 0,
  deduction_days numeric(4,2) default 0,    -- 0.25 / 0.5 / 1  (مش جنيه)
  note text, source text default 'kiosk', approved boolean default false,
  recorded_by uuid references auth.users(id), created_at timestamptz default now(),
  unique (employee_id, work_date)
);
alter table attendance add column if not exists check_out time;
alter table attendance add column if not exists deduction_days numeric(4,2) default 0;
alter table attendance drop column if exists deduction_amount;   -- شيل الجنيه القديم
create index if not exists idx_att_date on attendance(work_date);

-- ---- 6) Audit ----
create table if not exists audit_log (
  id bigint generated by default as identity primary key,
  actor uuid, action text not null, entity text, entity_id text,
  details jsonb, created_at timestamptz default now()
);

-- =====================================================================
--  7) do_checkin — بيسجّل الخصم ككسر يوم (مفيش مرتب هنا خالص)
-- =====================================================================
create or replace function do_checkin(p_emp bigint, p_pin text)
returns jsonb language plpgsql security definer set search_path=public, extensions as $$
declare
  s_from time; s_to time; s_start time; s_absent time;
  v_now timestamp; v_date date; v_time time; v_min int; v_late int;
  v_tier jsonb; v_tiers jsonb; v_status text:='pending'; v_label text:=''; v_cut numeric:=0; v_name text;
begin
  if not exists (select 1 from employees where id=p_emp and active
                 and pin_hash=crypt(p_pin,pin_hash)) then
    return jsonb_build_object('error','bad_pin','message','PIN غلط.');
  end if;
  select (value#>>'{}')::time into s_from   from settings where key='checkin_from';
  select (value#>>'{}')::time into s_to     from settings where key='checkin_to';
  select (value#>>'{}')::time into s_start  from settings where key='work_start';
  select (value#>>'{}')::time into s_absent from settings where key='absent_after';
  select value into v_tiers from settings where key='late_tiers';

  v_now := now() at time zone 'Africa/Cairo';
  v_date := v_now::date; v_time := v_now::time;
  v_min := extract(hour from v_now)::int*60 + extract(minute from v_now)::int;

  if v_time < s_from or v_time > s_to then
    return jsonb_build_object('error','window_closed','message',
      'نافذة التسجيل ('||to_char(s_from,'HH24:MI')||'–'||to_char(s_to,'HH24:MI')||') مقفولة دلوقتي.');
  end if;
  if exists (select 1 from attendance where employee_id=p_emp and work_date=v_date) then
    return jsonb_build_object('error','already','message','سجّلت حضورك النهاردة بالفعل.');
  end if;

  v_late := greatest(0, v_min - (extract(hour from s_start)::int*60 + extract(minute from s_start)::int));
  if v_time >= s_absent then v_status:='pending'; v_label:='بعد 10:00 · موافقة المدير'; v_cut:=0;
  else
    for v_tier in select * from jsonb_array_elements(v_tiers) loop
      if v_late <= (v_tier->>'upto')::int then
        v_status:=v_tier->>'status'; v_label:=v_tier->>'label'; v_cut:=(v_tier->>'cut')::numeric; exit;
      end if;
    end loop;
  end if;

  select name into v_name from employees where id=p_emp;
  insert into attendance(employee_id,work_date,check_in,status,late_minutes,deduction_days,source,approved)
  values (p_emp,v_date,v_time,v_status,v_late,v_cut,'kiosk',false);
  insert into audit_log(actor,action,entity,entity_id,details)
  values (null,'checkin','attendance',p_emp::text,jsonb_build_object('date',v_date,'time',v_time,'status',v_status));

  return jsonb_build_object('ok',true,'name',v_name,'status',v_status,'label',v_label,
    'time',to_char(v_time,'HH24:MI'),'lateMin',v_late,'deductionDays',v_cut);
end $$;

-- =====================================================================
--  8) سلطة الـ Owner: حالة خاصة / تصفية غياب يوم معيّن
-- =====================================================================
create or replace function owner_set_special(p_emp bigint, p_date date, p_status text, p_note text default 'حالة خاصة')
returns jsonb language plpgsql security definer set search_path=public as $$
begin
  if not is_owner() then return jsonb_build_object('error','owner_only','message','للـ Owner فقط.'); end if;
  insert into attendance(employee_id,work_date,status,deduction_days,note,source,approved,recorded_by)
  values (p_emp,p_date,p_status,0,p_note,'owner',true,auth.uid())
  on conflict (employee_id,work_date) do update
    set status=excluded.status, deduction_days=0, note=excluded.note, source='owner', approved=true, recorded_by=auth.uid();
  insert into audit_log(actor,action,entity,entity_id,details)
  values (auth.uid(),'owner_special','attendance',p_emp::text,jsonb_build_object('date',p_date,'status',p_status,'note',p_note));
  return jsonb_build_object('ok',true);
end $$;

-- =====================================================================
--  9) RLS
-- =====================================================================
alter table app_admins enable row level security;
alter table settings enable row level security;
alter table employees enable row level security;
alter table salaries enable row level security;
alter table attendance enable row level security;
alter table audit_log enable row level security;

drop policy if exists admins_hr on app_admins;
create policy admins_hr on app_admins for all to authenticated using (is_hr()) with check (is_hr());
drop policy if exists settings_read on settings;
drop policy if exists settings_write on settings;
create policy settings_read on settings for select to anon,authenticated using (true);
create policy settings_write on settings for all to authenticated using (is_hr()) with check (is_hr());
drop policy if exists emp_hr on employees;
create policy emp_hr on employees for all to authenticated using (is_hr()) with check (is_hr());

-- المرتبات: الـ OWNER بس
drop policy if exists sal_owner on salaries;
create policy sal_owner on salaries for all to authenticated using (is_owner()) with check (is_owner());

drop policy if exists att_hr on attendance;
create policy att_hr on attendance for all to authenticated using (is_hr()) with check (is_hr());
drop policy if exists audit_sel on audit_log;
create policy audit_sel on audit_log for select to authenticated using (is_hr());

-- ---- 10) Grants ----
grant usage on schema public to anon, authenticated;
grant select on kiosk_employees, settings to anon, authenticated;
grant select, insert, update, delete
  on employees, attendance, settings, app_admins, audit_log, salaries to authenticated;
grant usage, select on all sequences in schema public to authenticated;
grant execute on function do_checkin(bigint,text) to anon, authenticated;
grant execute on function owner_set_special(bigint,date,text,text) to authenticated;
revoke all on function set_employee_pin(bigint,text) from public;

-- =====================================================================
--  تم. الخطوة اليدوية: حسابين (Authentication → Add user) ثم:
--   -- حسابك انت (Owner — يشوف كل حاجة):
--   insert into app_admins(user_id,name,role) values ('<OWNER-UID>','مهموض','owner');
--   -- حساب الـ HR (مايشوفش مرتبات):
--   insert into app_admins(user_id,name,role) values ('<HR-UID>','اسم الموظفة','hr');
-- =====================================================================


-- ========== الجزء 2/4 — الانصراف (Check-out) ==========
-- =====================================================================
--  Air Ocean Line — Module 2: الانصراف (Check-out)
--  patch إضافي — شغّله بعد schema v3.  SQL Editor → الصق → Run
--  (نافذة الانصراف وعمود check_out موجودين أصلًا من v3)
-- =====================================================================

create or replace function do_checkout(p_emp bigint, p_pin text)
returns jsonb language plpgsql security definer set search_path=public, extensions as $$
declare
  s_from time; s_to time; s_grace time;
  v_now timestamp; v_date date; v_time time; v_rec record; v_name text; v_note text;
begin
  -- 1) PIN
  if not exists (select 1 from employees where id=p_emp and active and pin_hash=crypt(p_pin,pin_hash)) then
    return jsonb_build_object('error','bad_pin','message','PIN غلط.');
  end if;

  select (value#>>'{}')::time into s_from  from settings where key='checkout_from';
  select (value#>>'{}')::time into s_to    from settings where key='checkout_to';
  select (value#>>'{}')::time into s_grace from settings where key='checkout_grace_to';

  v_now := now() at time zone 'Africa/Cairo';
  v_date := v_now::date; v_time := v_now::time;

  -- 2) لازم يكون جوّه نافذة الانصراف
  if v_time < s_from or v_time > s_to then
    return jsonb_build_object('error','window_closed','message',
      'نافذة الانصراف ('||to_char(s_from,'HH24:MI')||'–'||to_char(s_to,'HH24:MI')||') مقفولة دلوقتي.');
  end if;

  -- 3) لازم يكون سجّل حضور الأول
  select * into v_rec from attendance where employee_id=p_emp and work_date=v_date;
  if not found then
    return jsonb_build_object('error','no_checkin','message','لازم تسجّل حضور الأول قبل الانصراف.');
  end if;
  if v_rec.check_out is not null then
    return jsonb_build_object('error','already_out','message','سجّلت انصرافك بالفعل ('||to_char(v_rec.check_out,'HH24:MI')||').');
  end if;

  -- انصراف 4:30–5:00 = عادي بدون خصم (v_note للتوضيح فقط)
  v_note := case when v_time <= s_grace then 'انصراف مبكر ضمن السماح' else null end;

  update attendance set check_out = v_time,
    note = coalesce(note, v_note)
  where employee_id=p_emp and work_date=v_date;

  insert into audit_log(actor,action,entity,entity_id,details)
  values (null,'checkout','attendance',p_emp::text, jsonb_build_object('date',v_date,'time',v_time));

  select name into v_name from employees where id=p_emp;
  return jsonb_build_object('ok',true,'name',v_name,'time',to_char(v_time,'HH24:MI'),
    'grace', (v_time <= s_grace));
end $$;

grant execute on function do_checkout(bigint, text) to anon, authenticated;

-- ملاحظة: قواعد الخصم للنسيان المتكرر (التالتة في الشهر = ربع يوم) والانصراف المبكر
-- بدون إذن بتتطبّق في القفل الشهري (موديول 5) وموديول الإذن (موديول 3)، لأنها بتعتمد عليهم.


-- ========== الجزء 3/4 — الإذن + تحديث do_checkout ==========
-- =====================================================================
--  Air Ocean Line — Module 3: الإذن (Early-leave Permission)
--  شغّله بعد schema v3 + موديول 2.  SQL Editor → الصق → Run
-- =====================================================================

create table if not exists permissions (
  id bigint generated by default as identity primary key,
  employee_id bigint not null references employees(id) on delete cascade,
  perm_date date not null,
  hours numeric(3,1),               -- 1 أو 2 (عدد ساعات الانصراف المبكر)
  start_time time, end_time time,   -- اختياري: وقت محدد
  reason text,
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  decided_by uuid references auth.users(id), decided_at timestamptz,
  created_at timestamptz default now()
);
create index if not exists idx_perm_emp_date on permissions(employee_id, perm_date);

-- ---- طلب إذن (الموظف عبر الكيوسك — anon) ----
create or replace function request_permission(
  p_emp bigint, p_pin text, p_date date,
  p_hours numeric default null, p_start time default null, p_end time default null, p_reason text default null)
returns jsonb language plpgsql security definer set search_path=public, extensions as $$
declare v_max int; v_cnt int; v_name text;
begin
  if not exists (select 1 from employees where id=p_emp and active and pin_hash=crypt(p_pin,pin_hash)) then
    return jsonb_build_object('error','bad_pin','message','PIN غلط.');
  end if;
  select (value#>>'{}')::int into v_max from settings where key='monthly_permission_max';

  -- الحد الأقصى الشهري (معلّق + معتمد)
  select count(*) into v_cnt from permissions
   where employee_id=p_emp and status in ('pending','approved')
     and date_trunc('month',perm_date)=date_trunc('month',p_date);
  if v_cnt >= coalesce(v_max,3) then
    return jsonb_build_object('error','max','message','وصلت الحد الأقصى للإذن الشهر ('||coalesce(v_max,3)||' مرات).');
  end if;

  -- مش في يومين متتاليين
  if exists (select 1 from permissions where employee_id=p_emp and status in ('pending','approved')
             and perm_date in (p_date - 1, p_date + 1)) then
    return jsonb_build_object('error','consecutive','message','مينفعش إذن في يومين ورا بعض.');
  end if;

  -- مش نفس اليوم مرتين
  if exists (select 1 from permissions where employee_id=p_emp and perm_date=p_date and status in ('pending','approved')) then
    return jsonb_build_object('error','dup','message','فيه طلب إذن لنفس اليوم موجود بالفعل.');
  end if;

  insert into permissions(employee_id,perm_date,hours,start_time,end_time,reason)
  values (p_emp,p_date,p_hours,p_start,p_end,p_reason);
  insert into audit_log(actor,action,entity,entity_id,details)
  values (null,'permission_request','permissions',p_emp::text,jsonb_build_object('date',p_date,'hours',p_hours));
  select name into v_name from employees where id=p_emp;
  return jsonb_build_object('ok',true,'name',v_name,'message','تم إرسال الطلب — في انتظار موافقة المدير.');
end $$;
grant execute on function request_permission(bigint,text,date,numeric,time,time,text) to anon, authenticated;

-- ---- قرار المدير (HR/Owner) ----
create or replace function decide_permission(p_id bigint, p_approve boolean)
returns jsonb language plpgsql security definer set search_path=public as $$
begin
  if not is_hr() then return jsonb_build_object('error','forbidden','message','للإدارة فقط.'); end if;
  update permissions set status = case when p_approve then 'approved' else 'rejected' end,
    decided_by=auth.uid(), decided_at=now() where id=p_id;
  insert into audit_log(actor,action,entity,entity_id,details)
  values (auth.uid(),'permission_decide','permissions',p_id::text,jsonb_build_object('approve',p_approve));
  return jsonb_build_object('ok',true);
end $$;
grant execute on function decide_permission(bigint,boolean) to authenticated;

-- ---- RLS ----
alter table permissions enable row level security;
drop policy if exists perm_hr on permissions;
create policy perm_hr on permissions for all to authenticated using (is_hr()) with check (is_hr());
grant select, insert, update, delete on permissions to authenticated;

-- =====================================================================
--  تحديث do_checkout: لو فيه إذن معتمد النهاردة → انصراف مبكر بدون خصم
-- =====================================================================
create or replace function do_checkout(p_emp bigint, p_pin text)
returns jsonb language plpgsql security definer set search_path=public, extensions as $$
declare
  s_from time; s_to time; s_grace time;
  v_now timestamp; v_date date; v_time time; v_rec record; v_name text; v_perm boolean;
begin
  if not exists (select 1 from employees where id=p_emp and active and pin_hash=crypt(p_pin,pin_hash)) then
    return jsonb_build_object('error','bad_pin','message','PIN غلط.');
  end if;

  v_now := now() at time zone 'Africa/Cairo';
  v_date := v_now::date; v_time := v_now::time;

  select * into v_rec from attendance where employee_id=p_emp and work_date=v_date;
  if not found then return jsonb_build_object('error','no_checkin','message','لازم تسجّل حضور الأول قبل الانصراف.'); end if;
  if v_rec.check_out is not null then
    return jsonb_build_object('error','already_out','message','سجّلت انصرافك بالفعل ('||to_char(v_rec.check_out,'HH24:MI')||').');
  end if;

  -- إذن معتمد النهاردة؟
  select exists(select 1 from permissions where employee_id=p_emp and perm_date=v_date and status='approved') into v_perm;

  if v_perm then
    update attendance set check_out=v_time, note=coalesce(note,'انصراف مبكر بإذن معتمد')
      where employee_id=p_emp and work_date=v_date;
    insert into audit_log(actor,action,entity,entity_id,details)
    values (null,'checkout_permission','attendance',p_emp::text,jsonb_build_object('date',v_date,'time',v_time));
    select name into v_name from employees where id=p_emp;
    return jsonb_build_object('ok',true,'name',v_name,'time',to_char(v_time,'HH24:MI'),'byPermission',true);
  end if;

  -- عادي: لازم جوّه نافذة الانصراف
  select (value#>>'{}')::time into s_from  from settings where key='checkout_from';
  select (value#>>'{}')::time into s_to    from settings where key='checkout_to';
  select (value#>>'{}')::time into s_grace from settings where key='checkout_grace_to';
  if v_time < s_from or v_time > s_to then
    return jsonb_build_object('error','window_closed','message',
      'نافذة الانصراف ('||to_char(s_from,'HH24:MI')||'–'||to_char(s_to,'HH24:MI')||') مقفولة، ومفيش إذن معتمد.');
  end if;

  update attendance set check_out=v_time,
    note=coalesce(note, case when v_time<=s_grace then 'انصراف مبكر ضمن السماح' else null end)
   where employee_id=p_emp and work_date=v_date;
  insert into audit_log(actor,action,entity,entity_id,details)
  values (null,'checkout','attendance',p_emp::text,jsonb_build_object('date',v_date,'time',v_time));
  select name into v_name from employees where id=p_emp;
  return jsonb_build_object('ok',true,'name',v_name,'time',to_char(v_time,'HH24:MI'),'grace',(v_time<=s_grace));
end $$;
grant execute on function do_checkout(bigint, text) to anon, authenticated;


-- ========== الجزء 4/4 — الأجازات (Cover) + تصنيف الغياب ==========
-- =====================================================================
--  Air Ocean Line — Module 4: الأجازات (Cover) + تصنيف الغياب
--  شغّله بعد v3 + موديول 2 + موديول 3.  SQL Editor → الصق → Run
-- =====================================================================

-- وسّع حالات الحضور: زوّدنا مأمورية (mission) + مرضي (sick)
alter table attendance drop constraint if exists attendance_status_check;
alter table attendance add constraint attendance_status_check
  check (status in ('present','late','absent','leave','pending','mission','sick'));

-- ---- جدول طلبات الأجازة ----
create table if not exists leave_requests (
  id bigint generated by default as identity primary key,
  employee_id bigint not null references employees(id) on delete cascade,
  from_date date not null, to_date date not null,
  days int not null check (days>0),
  cover_employee_id bigint references employees(id),
  reason text,
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  decided_by uuid references auth.users(id), decided_at timestamptz,
  created_at timestamptz default now(),
  check (to_date>=from_date),
  check (cover_employee_id is null or cover_employee_id<>employee_id)
);
create index if not exists idx_leave_emp on leave_requests(employee_id);

-- ---- طلب أجازة (الموظف عبر الكيوسك) ----
create or replace function request_leave(
  p_emp bigint, p_pin text, p_from date, p_to date, p_cover bigint, p_reason text default null)
returns jsonb language plpgsql security definer set search_path=public, extensions as $$
declare v_today date; v_days int; v_max int; v_used int; v_name text;
begin
  if not exists (select 1 from employees where id=p_emp and active and pin_hash=crypt(p_pin,pin_hash)) then
    return jsonb_build_object('error','bad_pin','message','PIN غلط.');
  end if;
  if p_cover is null then return jsonb_build_object('error','no_cover','message','لازم تختار الموظف اللي هيغطّيك.'); end if;
  if p_cover = p_emp then return jsonb_build_object('error','self_cover','message','مينفعش تغطّي نفسك.'); end if;
  if p_to < p_from then return jsonb_build_object('error','range','message','تاريخ خطأ.'); end if;

  v_today := (now() at time zone 'Africa/Cairo')::date;
  -- 24 ساعة على الأقل (يبدأ من بكرة على الأقل)
  if p_from <= v_today then
    return jsonb_build_object('error','notice','message','لازم تقدّم الطلب قبلها بيوم على الأقل.');
  end if;

  -- عدد الأيام (بدون الجمعة)
  select count(*) into v_days from generate_series(p_from,p_to,interval '1 day') g where extract(dow from g)<>5;
  if v_days<1 then return jsonb_build_object('error','range','message','مفيش أيام عمل في المدى ده.'); end if;

  -- الحد الأقصى الشهري
  select (value#>>'{}')::int into v_max from settings where key='monthly_leave_max';
  select coalesce(sum(days),0) into v_used from leave_requests
    where employee_id=p_emp and status in ('pending','approved')
      and date_trunc('month',from_date)=date_trunc('month',p_from);
  if v_used + v_days > coalesce(v_max,2) then
    return jsonb_build_object('error','max','message','تعدّيت الحد الشهري للأجازات ('||coalesce(v_max,2)||' يوم).');
  end if;

  insert into leave_requests(employee_id,from_date,to_date,days,cover_employee_id,reason)
  values (p_emp,p_from,p_to,v_days,p_cover,p_reason);
  insert into audit_log(actor,action,entity,entity_id,details)
  values (null,'leave_request','leave_requests',p_emp::text,jsonb_build_object('from',p_from,'to',p_to,'days',v_days,'cover',p_cover));
  select name into v_name from employees where id=p_emp;
  return jsonb_build_object('ok',true,'name',v_name,'days',v_days,'message','تم إرسال طلب الأجازة — في انتظار الموافقة.');
end $$;
grant execute on function request_leave(bigint,text,date,date,bigint,text) to anon, authenticated;

-- ---- قرار المدير على الأجازة ----
create or replace function decide_leave(p_id bigint, p_approve boolean)
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_req record; d date;
begin
  if not is_hr() then return jsonb_build_object('error','forbidden','message','للإدارة فقط.'); end if;
  select * into v_req from leave_requests where id=p_id;
  if not found then return jsonb_build_object('error','notfound'); end if;

  if p_approve then
    for d in select g::date from generate_series(v_req.from_date,v_req.to_date,interval '1 day') g where extract(dow from g)<>5 loop
      insert into attendance(employee_id,work_date,status,deduction_days,source,approved,note)
      values (v_req.employee_id,d,'leave',0,'leave',true,'أجازة معتمدة')
      on conflict (employee_id,work_date) do update set status='leave',deduction_days=0,approved=true,note='أجازة معتمدة';
    end loop;
    update employees set leave_balance = greatest(0, leave_balance - v_req.days) where id=v_req.employee_id;
  end if;

  update leave_requests set status=case when p_approve then 'approved' else 'rejected' end,
    decided_by=auth.uid(), decided_at=now() where id=p_id;
  insert into audit_log(actor,action,entity,entity_id,details)
  values (auth.uid(),'leave_decide','leave_requests',p_id::text,jsonb_build_object('approve',p_approve));
  return jsonb_build_object('ok',true);
end $$;
grant execute on function decide_leave(bigint,boolean) to authenticated;

-- ---- تصنيف يوم (Pending Absence → أجازة/غياب/مأمورية/مرضي) ----
create or replace function set_day_status(p_emp bigint, p_date date, p_kind text)
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_old text; v_ded numeric:=0;
begin
  if not is_hr() then return jsonb_build_object('error','forbidden','message','للإدارة فقط.'); end if;
  if p_kind not in ('leave','absent','mission','sick','present') then
    return jsonb_build_object('error','bad_kind'); end if;

  select status into v_old from attendance where employee_id=p_emp and work_date=p_date;
  v_ded := case when p_kind='absent' then 1 else 0 end;

  insert into attendance(employee_id,work_date,status,deduction_days,source,approved,note)
  values (p_emp,p_date,p_kind,v_ded,'hr',true,null)
  on conflict (employee_id,work_date) do update set status=p_kind, deduction_days=v_ded, source='hr', approved=true;

  -- تعديل رصيد الأجازة (يوم واحد)
  if p_kind='leave' and (v_old is distinct from 'leave') then
    update employees set leave_balance=greatest(0,leave_balance-1) where id=p_emp;
  elsif v_old='leave' and p_kind<>'leave' then
    update employees set leave_balance=leave_balance+1 where id=p_emp;
  end if;

  insert into audit_log(actor,action,entity,entity_id,details)
  values (auth.uid(),'classify','attendance',p_emp::text,jsonb_build_object('date',p_date,'kind',p_kind));
  return jsonb_build_object('ok',true);
end $$;
grant execute on function set_day_status(bigint,date,text) to authenticated;

-- ---- RLS ----
alter table leave_requests enable row level security;
drop policy if exists leave_hr on leave_requests;
create policy leave_hr on leave_requests for all to authenticated using (is_hr()) with check (is_hr());
grant select, insert, update, delete on leave_requests to authenticated;
